# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1000000000);
user_pref("app.update.lastUpdateTime.background-update-timer", 1000000000);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1000000000);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1000000000);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1256028341);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1000000000);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.download.manager.showAlertOnComplete", false);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.startup.homepage", "file:///etc/lesslinux/branding/browser_startup.html|http://www.google.de/firefox?client=firefox-a&rls=org.mozilla:en-US:official");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.3");
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("capability.policy.maonoscript.sites", "addons.mozilla.org flashgot.net google.com googlesyndication.com hotmail.com informaction.com live.com maone.net msn.com noscript.net passport.com passport.net passportimages.com yahoo.com yimg.com about: about:blank about:certerror about:config about:credits about:neterror about:plugins about:privatebrowsing about:sessionrestore chrome: file:// http://flashgot.net http://google.com http://googlesyndication.com http://hotmail.com http://informaction.com http://live.com http://maone.net http://msn.com http://noscript.net http://passport.com http://passport.net http://passportimages.com http://yahoo.com http://yimg.com https://flashgot.net https://google.com https://googlesyndication.com https://hotmail.com https://informaction.com https://live.com https://maone.net https://msn.com https://noscript.net https://passport.com https://passport.net https://passportimages.com https://yahoo.com https://yimg.com resource:");
user_pref("distribution.computerbild.bookmarksProcessed", true);
user_pref("downbar.function.donateTextInterval", "1246352333184");
user_pref("downbar.function.firstRun", false);
user_pref("downbar.function.soundCustomComplete", "file://");
user_pref("downbar.function.useTooltipOpacity", false);
user_pref("downbar.function.version", "0.9.6");
user_pref("downbar.function.virusExclude", "");
user_pref("downbar.function.virusLoc", "/opt/bin/clam_wrapper");
user_pref("downbar.function.virusScan", true);
user_pref("extensions.enabledItems", "langpack-de@firefox.mozilla.org:3.5,langpack-es-ES@firefox.mozilla.org:3.5,langpack-pl@firefox.mozilla.org:3.5,langpack-ru@firefox.mozilla.org:3.5,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.3");
user_pref("extensions.lastAppVersion", "3.5.3");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.prefetch-next", false);
user_pref("noscript.gtemp", "");
user_pref("noscript.policynames", "");
user_pref("noscript.temp", "");
user_pref("noscript.version", "1.9.9.11");
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.item.cookies", true);
user_pref("privacy.item.offlineApps", true);
user_pref("privacy.item.passwords", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("security.dialog_enable_delay", 5000);
user_pref("startup.homepage_welcome_url", "file:///etc/lesslinux/branding/browser_startup.html");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1258665966);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");

