#!/static/bin/ash	
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/static/bin:/static/sbin
		
. /etc/rc.defaults
. /etc/rc.subr/extractbootparams
. /etc/rc.subr/colors		

for i in /etc/xinitrc.d/[0-9][0-9][0-9][0-9]-*.?? ; do
	provides="` cat $i | grep '#lesslinux provides' | awk '{print $3}' `"
	if echo "$skipservices" | grep -q '|'$provides'|' ; then
		echo "Skipping $provides"
	else
		$i start
	fi
done

xsetroot -solid darkgray
setxkbmap -layout "$xkbmap"
killall -9 compton
killall -9 xcompmgr

terminal=/usr/bin/xterm
[ -x "$terminal" ] || terminal=/usr/bin/Terminal
"$terminal"
		
		
