desktop_background_png="/etc/lesslinux/branding/desktop.png"
desktop_background_jpg="/etc/lesslinux/branding/desktop.jpg"
install_background_png="/etc/lesslinux/branding/desktop.png"
startup_background_png="/etc/lesslinux/branding/desktop.png"
browser_startup_file="/etc/lesslinux/branding/browser_startup.html"
browser_too_old_file="/etc/lesslinux/branding/browser_too_old.html"
browser_about_file="/etc/lesslinux/branding/about.html"
