#!/bin/bash
#
# Copyright (c) 2010 AVIRA GmbH
#
# Modifications by Mattias Schlenker

# This script updates the Rescue-System

DEBUGTTY="/dev/null"


display_help ()
{
	echo " "
	echo "`basename $0` - Updates AVIRA AntiVir the Rescue-System"
	echo " "
	echo "Usage:  $0"
	echo " "
	echo "Other options:"
	echo "   -h|--help       (this help message)"
}

# main
if [ ! -x "./avupdate.bin" ]
then
	cd ` dirname $0  ` 
fi
LICENSE_CHECK='--check-product'

for PARAM in "$@" ; do
	case ${PARAM} in
		-h|--help)
			display_help
			exit 0
		;;
	esac
done

# 	start update for unix rescues-system
echo "Updating, please wait ... "
./avupdate.bin --log=/tmp/avupdate.log --config=avupdate.conf \
	--product-file=/idx/rescuesystem_cb-linux_glibc22-en.idx \
	--product-info-file=/idx/rescuesystem_cb-linux_glibc22-en.info.gz \
	--skip-master-file $@ 
retcode="$?"
echo "$retcode" > /tmp/avupdate.ret 
